### ISSUE TITLE
Motivational Quotes API

### ISSUE THREAD

**Issue by acushlakoncept** [MLH-Fellowship/pod3.1.4-DiscordBot#4]
It will be nice to find a suitable motivational quotes API that our Bot will use to send messages at certain hours of the day.
I am thinking Morning, Afternoon and Night

**Comment by Youngprinnce** [comment]
@acushlakoncept  I will take on this task

**Comment by acushlakoncept** [comment]
Thank you for working on this issue, I will now close it.

**Comment by acushlakoncept** [comment]
Do you think you can update your code to the **modified** below, I noticed you logged the bot in twice.

Since we already have `client.login(process.env.TOKEN);` I don't think we need it again inside the `scheduleMessage` function.

### Original

```javascript
client.login(process.env.TOKEN);

const scheduleMessage = async () => {
	const quote = await getQuote();
	client.login(process.env.TOKEN).then(() => {
		const guild = client.guilds.cache.get(guiddId);
		const channel = guild.channels.cache.get(channelId);
		channel.send(quote);
	});
};
```

### modified

```javascript
client.login(process.env.TOKEN);

// Program to send message
const scheduleMessage = async () => {
	const quote = await getQuote();
	const guild = client.guilds.cache.get(guiddId);
	const channel = guild.channels.cache.get(channelId);
	channel.send(quote);
};
```
